projects:
  reactamplified:
    schemaPath: src/graphql/schema.json
    includes:
      - todo
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
